# Generated by Django 4.2.7 on 2025-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload book cover image', null=True, upload_to='books/covers/', verbose_name='Book Cover Image'),
        ),
        migrations.AddField(
            model_name='book',
            name='placeholder_pdf',
            field=models.FileField(blank=True, help_text='PDF file to be sent as eBook placeholder', null=True, upload_to='books/pdfs/', verbose_name='eBook PDF File'),
        ),
    ]
